### ISSUE TITLE
Values are not fetched

### ISSUE THREAD

**Issue by julienmary** [InfluxGraph/influxgraph#27]
I use the docker instance, hosted on a server collecting data from sensors. Data as collected through influxdb http API calls.

My influxdb series look like : 
```
yoctopuce,ip=10.120.237.131,name=YHUBGSM3-70AA4
yoctopuce,ip=10.120.249.139,name=YHUBGSM3-70AA4
...

```
My fields Keys are :
```
> SHOW FIELD KEYS FROM yoctopuce
name: yoctopuce
fieldKey                      fieldType
--------                      ---------
pm1                           float
pm10                          float
pm25                          float
value1                        float
```

Render output is truncated as follows : (no values after | )
http://xxx.xxx.xxx.xxx:8000/render?from=-1h&target=*.yoctopuce.*.pm25&format=raw
```
10.109.242.23.yoctopuce.YHUBGSM3-70AE0.pm25,1491818207,1491821807,10|
10.120.237.131.yoctopuce.YHUBGSM3-70AA4.pm25,1491818207,1491821807,10|
```
Whereas the request :
`SELECT mean("pm25") FROM "yoctopuce" WHERE  time > now() - 1h GROUP BY TIME(10s)`
would send back : 
```
name: yoctopuce
time                mean
----                ----
1491819050000000000 8.864
1491819060000000000 9.34
1491819070000000000 9.131
1491819080000000000 8.975
1491819090000000000 8.977
1491819100000000000 8.854
1491819110000000000 9.286
1491819120000000000 8.791
1491819130000000000 10.268
1491819140000000000 9.761
1491819150000000000 10.616
1491819160000000000 11.169333333333334

```
My graphite-api.yaml is :
```
finders:
  - influxgraph.InfluxDBFinder
influxdb:
  host: dockerhost
  db: XXXXX
  user: XXXXX
  pass: XXXXX
  templates:
    # Default telegraf agent measurement types                                  
    #- "*.diskio. host.measurement.name.field*"                                 
    #- "*.disk. host.measurement.path.fstype.field*"                            
    #- "*.cpu. host.measurement.cpu.field*"                                     
    - "*.yoctopuce. *.measurement.name.field*"
    - ip.measurement.name.field*
  memcache:
    host: localhost
  log_file: /var/log/influxgraph/influxgraph.log
  log_level: debug
  deltas:
    86400 : 10
  aggregation_functions:
    \.min$ : min
    \.max$ : max
    \.last$ : last
    \.sum$ : sum
    \.mean$ : mean

```
What can possibly be wrong ?
