### ISSUE TITLE
504 Gateway Timeout with Influx Cloud Integration

### ISSUE THREAD

**Issue by hendolim** [InfluxGraph/influxgraph#30]
I am having problem connecting to influx Cloud cluster:
I keep getting 504 Gateway Time-out when querying. It seems that Gunicorn workers are timing out, but there's not specific explanations why it happened:
from `/var/log/graphite-api.log`:
```
[2017-05-08 20:58:55 +0000] [22] [CRITICAL] WORKER TIMEOUT (pid:292)
[2017-05-08 20:58:55 +0000] [22] [CRITICAL] WORKER TIMEOUT (pid:293)
```
Here is my `graphite-api.yaml`:
```
finders:
  - influxgraph.InfluxDBFinder
influxdb:
  db: graphite
  host: my-influxcloud.net
  port: 8086
  user: my-username
  pass: my-password
  ssl: true
```

I also keep getting certificate verification warning in the log, but I am not sure what's the behaviour of urllib (whether it terminates the connection or not):
```
/srv/graphite-pypy/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```
